routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('/', function(){
//     return view('welcome');
// });
Route::get('/', 'EmployeesController@index');
Route::resource('/employees', 'EmployeesController');

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;

class Employee extends Model
{
    use SoftDeletes;
    
    //
    protected $fillable = [
        'name',
        'salary',
        'position',
        'gender',
        'skills',
        'birthdate'
    ];
    public function getAgeAttribute()
    {
      return Carbon::parse($this->attributes['birthdate'])->age;
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Employee;
use DB;
class EmployeesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::all();
        $employee_counter = [];
        $employee_counter['total'] = Employee::count();
        $employee_counter['per_position'] = DB::table('employees')
                                            ->select(DB::raw("count(*) as count_position, position"))
                                            ->groupBy(DB::raw('position'))
                                            ->get();
        $colors = [];
        $labels = [];
        $values = [];
        foreach ($employee_counter['per_position'] as $key => $value) {
            $colors[] = $this->getRgbaForChartJs($value->count_position * rand());
            $labels[] = $value->position;
            $values[] = $value->count_position;
        }
        $colors = json_encode($colors);
        $labels = json_encode($labels);
        $values = json_encode($values);
        return view('Employees.index', compact('employees', 'employee_counter','colors','labels', 'values'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('Employees.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'name'=>'required',
            'birthdate'=> 'required',
            'salary' => 'required|integer',
            'position' => 'required',
        ]);
        $emp = new Employee([
            'name' => $request->get('name'),
            'salary'=> $request->get('salary'),
            'position'=> $request->get('position'),
            'birthdate' => $request->get('birthdate'),
            'gender' => $request->get('gender'),
            'skills' => json_encode($request->get('skills'))
        ]);
        $emp->save();
        return redirect('/employees')->with('success', 'Employee has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee = Employee::find($id);

        return view('employees.edit', compact('employee'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $request->validate([
            'name'=>'required',
            'birthdate'=> 'required',
            'salary' => 'required|integer',
            'position' => 'required',
        ]);
        $emp = Employee::find($id);
        $emp->name = $request->get('name');
        $emp->position = $request->get('position');
        $emp->salary = $request->get('salary');
        $emp->birthdate = $request->get('birthdate');
        $emp->gender = $request->get('gender');
        $emp->skills = json_encode($request->get('skills'));
        $emp->save();
        return redirect('/employees')->with('info', 'Employee has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $emp = Employee::find($id);
        $emp->delete();

        return redirect('/employees')->with('danger', 'Employee has been deleted');
    }


    /* Private Function */
    private function getRgbaForChartJs($num) {
        $hash = md5('color' . $num); // modify 'color' to get a different palette
        return 'rgba('.hexdec(substr($hash, 0, 2)).', '.hexdec(substr($hash, 2, 2)).', '.hexdec(substr($hash, 4, 2)).', 0.2)';
    }
    /* End Private Function */
}

resources/views/Employees/Element/index_js.blade.php
$(document).ready(function() {
    $('#table-employee').DataTable();
} );

var ctx = document.getElementById("positionChart");
var positionChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: {!!$labels!!},
        datasets: [{
            label: 'Count Employee Per Position',
            data: {!!$values!!},
            backgroundColor: {!!$colors!!},
            borderColor: {!!$colors!!},
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});

resources/views/Employees/create.blade.php
@extends('layouts.template')

@section('content')
    <div class="card">
        <div class="card-header">
            Add Employee
        </div>
        <div class="card-body">
            @if($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{ route('employees.store') }}">
                <div class="form-group">
                    @csrf
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" name="name"/>
                </div>
                <div class="form-group">
                    <label for="name">Position:</label>
                    <input type="text" class="form-control" name="position"/>
                </div>
                <div class="form-group">
                    <label for="name">Gender:</label>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="gender" id="gendermale" value="male" checked>
                        <label class="form-check-label" for="gendermale">Male</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="gender" id="genderfemale" value="female">
                        <label class="form-check-label" for="genderfemale">Female</label>
                    </div>
                </div>
                <div class="form-group">
                    <label for="name">Skills:</label>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" id="Laravel" value="laravel" name="skills[]">
                        <label class="form-check-label" for="Laravel">Laravel</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" id="CakePHP" value="cakephp" name="skills[]">
                        <label class="form-check-label" for="CakePHP">CakePHP</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" id="ReactNative" value="reactnative" name="skills[]">
                        <label class="form-check-label" for="ReactNative">React Native</label>
                    </div>
                </div>
                <div class="form-group">
                    <label for="name">Salary:</label>
                    <input type="numeric" class="form-control" name="salary"/>
                </div>
                <div class="form-group">
                    <label for="name">Birthdate:</label>
                    <input type="date" class="form-control" name="birthdate" value=""/>
                </div>
                <button type="submit" class="btn btn-primary">Add</button>
                <a class="btn btn-dark" href="{{url('employees')}}">Back</a>
            </form>
        </div>

    </div>

@stop

resources/views/Employees/edit.blade.php
@extends('layouts.template')

@section('content')
    <div class="card">
        <div class="card-header">
            Edit Employee
        </div>
        <div class="card-body">
            @if($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{ route('employees.update', $employee->id) }}">
                @method('PATCH')
                @csrf
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" name="name" value="{{$employee->name}}"/>
                </div>
                <div class="form-group">
                    <label for="name">Position:</label>
                    <input type="text" class="form-control" name="position" value="{{$employee->position}}"/>
                </div>
                <div class="form-group">
                    <label for="name">Gender:</label>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="gender" id="gendermale" value="male" {{$employee->gender == 'male' ? 'checked' : ''}}>
                        <label class="form-check-label" for="gendermale">Male</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="gender" id="genderfemale" value="female" {{$employee->gender == 'female' ? 'checked' : ''}}>
                        <label class="form-check-label" for="genderfemale">Female</label>
                    </div>
                </div>
                <div class="form-group">
                    <label for="name">Skills:</label>
                    <?php $skills = json_decode($employee->skills,TRUE);
                        if(!is_array($skills)) $skills = [];
                    ?>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" id="Laravel" value="laravel" name="skills[]" {{in_array('laravel',$skills) ? 'checked' : ''}}>
                        <label class="form-check-label" for="Laravel">Laravel</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" id="CakePHP" value="cakephp" name="skills[]" {{in_array('cakephp',$skills) ? 'checked' : ''}}>
                        <label class="form-check-label" for="CakePHP">CakePHP</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" id="ReactNative" value="reactnative" name="skills[]" {{in_array('reactnative',$skills) ? 'checked' : ''}}>
                        <label class="form-check-label" for="ReactNative">React Native</label>
                    </div>
                </div>
                <div class="form-group">
                    <label for="name">Salary:</label>
                    <input type="numeric" class="form-control" name="salary" value="{{$employee->salary}}"/>
                </div>
                <div class="form-group">
                    <label for="name">Birthdate:</label>
                    <input type="date" class="form-control" name="birthdate" value="{{date('Y-m-d',strtotime($employee->birthdate))}}"/>
                </div>
                <button type="submit" class="btn btn-primary">Update</button>
                <a class="btn btn-dark" href="{{url('employees')}}">Back</a>
            </form>
        </div>

    </div>

@stop

resources/views/Employees/index.blade.php
@extends('layouts.template')

@section('content')
    <div class="container-body">
        @if(session()->get('success'))
            <div class="alert alert-success">
              {{ session()->get('success') }}
            </div><br />
        @endif
        <div class="row" style="margin-bottom:10px">
            <canvas id="positionChart" width="400" height="100"></canvas>
        </div>
        <div class="row" style="margin-bottom: 5px;">
            <div class="col-lg-4">
                <a class="btn btn-primary" href="{{ url('/employees/create') }}">Add Employee</a>
            </div>
            <div class="col-lg-8 text-right">
                <h3>Total: {{$employee_counter['total']}}</h3>

                    @foreach($employee_counter['per_position'] as $pos)
                        {{$pos->position}} : {{$pos->count_position}} <br/>
                    @endforeach

            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <table id="table-employee" class="display" style="width:100%">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Position</th>
                            <th>Gender</th>
                            <th>Skills</th>
                            <th>Age</th>
                            <th>Salary</th>
                            <th style="width:120px">#</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($employees as $employee)
                            <tr>
                                <td>{{$employee->name}}</td>
                                <td>{{$employee->position}}</td>
                                <td>{{$employee->gender}}</td>
                                <td>
                                    <?php $skills = json_decode($employee->skills, TRUE) ?>
                                    @if(is_array($skills))
                                        @foreach($skills as $skill)
                                            <span class="badge badge-success">{{$skill}}</span>
                                        @endforeach
                                    @else
                                        <span class="badge badge-danger">No Skill WTF</span>
                                    @endif
                                </td>
                                <td>{{$employee->age}}</td>
                                <td>200000</td>
                                <td>
                                    <a class="btn btn-xs btn-primary"href="{{route('employees.edit',$employee->id)}}">Edit</a>
                                    <form action="{{ route('employees.destroy', $employee->id)}}" method="post" style="display:inline">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger" type="submit">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>

@stop

@section('js-per-page')
    @include('Employees/Element/index_js')
@stop

resources/views/Layouts/template.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>Employees</title>
        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet" type="text/css">
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
        <link href="{{ asset('css/datatables.min.css') }}" rel="stylesheet">
    </head>
    <body>
        <div class="container">
            @yield('content')
        </div>
    </body>
    <script type="text/javascript" src="{{ asset('js/app.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/jquery-3.3.1.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/DataTables/datatables.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/Chart.min.js') }}"></script>
    <script>
    $.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
});
    @yield('js-per-page')
    </script>
</html>